import CustomButton from "@/components/shared/Button";
import { BILL_TYPE, GiftCardDetails } from "@/constants/types";
import toast from "react-hot-toast";
import { LuCopy } from "react-icons/lu";
import Image from "next/image";
import images from "../../../../public/images";
import html2canvas from "html2canvas";
import { format } from "date-fns";
import { createRoot } from "react-dom/client";

type StageThreeProps = {
  setStage: (stage: "one" | "two" | "three") => void;
  phone?: string;
  network?: string;
  cableProvider?: string;
  internetProvider?: string;
  amount: string;
  type: BILL_TYPE;
  checkoutMessage?: string;
  electricityResCode?: string;
  setNetwork?: (network: string) => void;
  giftCardDetails?: GiftCardDetails;
};

const BillStageThree: React.FC<StageThreeProps> = ({
  setStage,
  phone,
  network,
  amount,
  cableProvider,
  internetProvider,
  type,
  checkoutMessage,
  electricityResCode,
  setNetwork = () => {},
}) => {
  const getPurchaseMessage = () => {
    switch (type) {
      case "airtime":
        return "Airtime Purchase";
      case "internationalAirtime":
        return `${network} Purchase`;
      case "data":
        return "Mobile Data Purchase";
      case "cable":
        return `${cableProvider} Subscription`;
      case "electricity":
        return `Electricity Purchase`;
      case "internet":
        return `Internet Purchase`;
      case "giftcard":
        return `Gift Card Purchase`;
      default:
        return `${internetProvider} Internet Purchase`;
    }
  };

  const getSubText = () => {
    switch (type) {
      case "airtime":
        return `Glo Airtime for ${phone}`;
      case "data":
        return checkoutMessage;
      case "cable":
        return checkoutMessage;
      case "electricity":
        return "worth of electricity recharge";
      case "internet":
        return checkoutMessage;
    }
  };


// Add Receipt Template Component
const ReceiptTemplate = ({ 
  type, 
  amount, 
  network, 
  phone, 
  cableProvider, 
  checkoutMessage,
  electricityResCode,
  timestamp = new Date()
}: {
  type: BILL_TYPE;
  amount: string;
  network?: string;
  phone?: string;
  cableProvider?: string;
  checkoutMessage?: string;
  electricityResCode?: string;
  timestamp?: Date;
}) => {
  const formattedDate = format(timestamp, "EEEE, MMMM d, yyyy h:mm a");

  return (
    <div id="receipt-container" className="flex flex-col max-w-md mx-auto overflow-hidden rounded-2xl shadow-lg">
      <div className="bg-amber-100 p-4 rounded-b-2xl relative">
        <div className="absolute -left-3 -top-1 w-6 h-6 bg-white rounded-full"></div>
        <div className="absolute -right-3 -top-1 w-6 h-6 bg-white rounded-full"></div>
        
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center bg-white p-2.5 rounded-lg">
            <Image 
              src={images.logo} 
              alt="logo" 
              className="h-12 w-auto font-bold"
              style={{ 
                objectFit: 'contain',
                width: 'auto',
                minWidth: '140px'
              }}
            />
          </div>
          <div className="text-gray-700 text-sm font-medium">
            Smart Banking
          </div>
        </div>
        
        <h1 className="text-xl font-bold text-center text-gray-800 mb-1">Transaction Receipt</h1>
        <p className="text-xs text-center text-gray-500">
          Generated by Nattypay on {formattedDate}
        </p>
      </div>

      <div className="bg-white">
        {[
          { label: "Transaction Type", value: type },
          { label: "Amount", value: `₦ ${amount?.toLocaleString()}` },
          { label: "Provider", value: network || cableProvider, show: !!(network || cableProvider) },
          { label: "Phone Number", value: phone, show: !!phone },
          { label: "Details", value: checkoutMessage, show: !!checkoutMessage },
          { label: "Recharge Code", value: electricityResCode, show: !!electricityResCode },
          { label: "Status", value: "Success", isStatus: true },
        ]
          .filter(item => item.show !== false)
          .map((detail, index) => (
            <div
              key={index}
              className="border-b border-gray-100 px-4 py-2 w-full flex items-center justify-between"
            >
              <p className="text-amber-300 text-xs font-medium">{detail.label}</p>
              {detail.isStatus ? (
                <span className="inline-flex items-center justify-center px-3 py-1.5 rounded-full text-xs font-medium text-green-600">
                  {detail.value}
                </span>
              ) : (
                <p className="text-gray-800 text-xs font-medium text-right">{detail.value}</p>
              )}
            </div>
          ))}
      </div>

      <div className="bg-white p-3 text-center border-t border-gray-100 rounded-b-2xl">
        <p className="text-xs text-gray-500 mb-1">
          If You Have Questions, Please Call Our 24/7 Contact Centre On <span className="text-amber-500">+2348134146906</span> Or Send Us Mail To <a href="mailto:support@nattypay.com" className="text-amber-500">support@nattypay.com</a>
        </p>
        <p className="text-xs text-gray-500">
          Thanks For Choosing Nattypay
        </p>
      </div>
    </div>
  );
};

// Add download and share handlers
const handleDownload = async (props: any) => {
  const tempDiv = document.createElement("div");
  tempDiv.style.position = "absolute";
  tempDiv.style.left = "-9999px";
  document.body.appendChild(tempDiv);

  const root = createRoot(tempDiv);
  root.render(<ReceiptTemplate {...props} />);

  try {
    await new Promise((resolve) => setTimeout(resolve, 100));
    const canvas = await html2canvas(tempDiv, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
    });

    const link = document.createElement("a");
    link.download = `nattypay-bill-${Date.now()}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  } catch (error) {
    console.error("Error generating PNG:", error);
  } finally {
    root.unmount();
    document.body.removeChild(tempDiv);
  }
};

const handleShare = async (props: any) => {
  const tempDiv = document.createElement("div");
  tempDiv.style.position = "absolute";
  tempDiv.style.left = "-9999px";
  document.body.appendChild(tempDiv);

  const root = createRoot(tempDiv);
  root.render(<ReceiptTemplate {...props} />);

  try {
    await new Promise((resolve) => setTimeout(resolve, 100));
    const canvas = await html2canvas(tempDiv, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
    });

    const blob = await new Promise<Blob>((resolve) => {
      canvas.toBlob((blob) => resolve(blob!), "image/png", 1.0);
    });

    if (navigator.share) {
      const file = new File([blob], "nattypay-bill-receipt.png", {
        type: "image/png",
      });
      await navigator.share({
        files: [file],
        title: "Transaction Receipt",
      });
    } else {
      const link = document.createElement("a");
      link.download = `nattypay-bill-${Date.now()}.png`;
      link.href = URL.createObjectURL(blob);
      link.click();
    }
  } catch (error) {
    console.error("Error sharing/generating PNG:", error);
  } finally {
    root.unmount();
    document.body.removeChild(tempDiv);
  }
};

  return (
    <div className="w-full max-2xs:mt-20 py-5 xs:py-10 h-full  flex items-center justify-center">
      <div className="w-[100%] sm:w-[85%] lg:w-[75%] xl:w-[65%] 2xl:w-[55%] h-full flex flex-col justify-center gap-8 rounded-lg sm:rounded-xl p-0 2xs:p-4 md:p-8">
        <div className="text-center flex flex-col items-center justify-center">
          <div
            className="flex items-center justify-center w-12 h-12 bg-bg-2600 rounded-full mb-4"
            style={{
              animation: "shadowBeat 1.5s ease-in-out infinite",
              boxShadow: "0 0 0 0 rgba(34, 197, 94, 0.7)", // Starting shadow
            }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 text-white"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M20 6L9 17l-5-5" />
            </svg>

            {/* Inline Keyframes */}
            <style>
              {`
      @keyframes shadowBeat {
        0%, 100% {
          box-shadow: 0 0 0 0 rgba(34, 197, 94, 0.7);
        }
        50% {
          box-shadow: 0 0 20px 10px rgba(34, 197, 94, 0.4);
        }
      }
    `}
            </style>
          </div>
          <p className="mt-2 text-xl font-bold text-text-1800">
            {getPurchaseMessage()}
          </p>
          <p className="text-xl text-text-1800 font-bold">Successful!</p>
        </div>

        <div className="flex text-text-200 dark:text-text-800   flex-col text-center">
          <p>
            You just purchase{" "}
            <span className="font-semibold dark:text-text-400">
              ₦ {amount?.toLocaleString()}
            </span>{" "}
          </p>
          <p>{getSubText()}</p>
          {type === "electricity" && electricityResCode && (
            <div className="flex items-center justify-center gap-2">
              <p>
                Recharge Code:{" "}
                <span className="text-text-1600">{electricityResCode}</span>
              </p>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(electricityResCode);
                  toast.success("Copied to clipboard", {
                    duration: 3000,
                  });
                }}
                className="transition-colors"
              >
                <LuCopy className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>

        

        <div className="flex justify-center gap-4">
  <CustomButton
    type="button"
    onClick={() => handleShare({
      type,
      amount,
      network,
      phone,
      cableProvider,
      checkoutMessage,
      electricityResCode
    })}
    className="w-full 2xs:w-[90%] xs:w-[80%] sm:w-[70%] border-2 text-text-1500 dark:text-text-200 dark:font-bold border-primary text-base 2xs:text-lg max-2xs:px-6 py-3.5"
  >
    Share Receipt
  </CustomButton>

  <CustomButton
    type="button"
    onClick={() => handleDownload({
      type,
      amount,
      network,
      phone,
      cableProvider,
      checkoutMessage,
      electricityResCode
    })}
    className="w-full 2xs:w-[90%] xs:w-[80%] sm:w-[70%] border-2 text-text-1500 dark:text-text-200 dark:font-bold border-primary text-base 2xs:text-lg max-2xs:px-6 py-3.5"
  >
    Download Receipt
  </CustomButton>

  <CustomButton
    type="button"
    onClick={() => {
      setNetwork("");
      setStage("one");
    }}
    className="w-full 2xs:w-[90%] xs:w-[80%] sm:w-[70%] border-2 text-text-1500 dark:text-text-200 dark:font-bold border-primary text-base 2xs:text-lg max-2xs:px-6 py-3.5"
  >
    Done
  </CustomButton>
</div>
      </div>
    </div>
  );
};

export default BillStageThree;
